DormitoryManagement/Controllers/AccessController.cs
using DormitoryManagement.Areas.Admin;
using DormitoryManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace DormitoryManagement.Controllers
{
    public class AccessController : Controller
    {
		private DormitoryManagementEntities _db = new DormitoryManagementEntities();

		// GET: Access/Logout
		public ActionResult Logout()
		{
			Session.Clear();//remove session
			return RedirectToAction("Login");
		}

		[RequireLogout]
		// GET: Access
		public ActionResult Login()
        {
            return View();
        }

		// POST: Access
		[HttpPost]
		[RequireLogout]
		[ValidateAntiForgeryToken]
		public ActionResult Login(string username, string password)
		{
			if (ModelState.IsValid)
			{
				var f_password = GetMD5(password);
				var data = _db.StudentAccounts.Where(s => s.UserName.Equals(username)).ToList();
				if (data.Count() > 0)
				{
					if (data.FirstOrDefault().IsLocked == 1)
					{
						ViewData["error"] = "Your account is enabled";
						return View();
					}
					else if (data.FirstOrDefault().Password.Equals(f_password))
					{
						//add session
						Session["username"] = data.FirstOrDefault().UserName;
						Session["idUser"] = data.FirstOrDefault().StudentID;
						Session["StudentImagePath"] = data.FirstOrDefault().ImagePath;
						data.FirstOrDefault().LoginAttempts = 0;
						_db.SaveChanges();

						return RedirectToRoute(new { Controller = "Home", action = "Index" });
					}
					else
					{
						data.FirstOrDefault().LoginAttempts += 1;
						if (data.FirstOrDefault().LoginAttempts == 5)
						{
							data.FirstOrDefault().IsLocked = 1;
						}
						_db.SaveChanges();

						ViewData["error"] = "Your username or password not correct";
						return View();
					}

				}
				else
				{
					ViewData["error"] = "Your email or password not correct";
					return View();
				}
			}
			return View();
		}

		//create a string MD5
		public static string GetMD5(string str)
		{
			MD5 md5 = new MD5CryptoServiceProvider();
			byte[] fromData = Encoding.UTF8.GetBytes(str);
			byte[] targetData = md5.ComputeHash(fromData);
			string byte2String = null;

			for (int i = 0; i < targetData.Length; i++)
			{
				byte2String += targetData[i].ToString("x2");

			}
			return byte2String;
		}
	}
}

DormitoryManagement/Views/Access/Login.cshtml
@{
    Layout = null;
    ViewBag.Title = "Login";
}
@model DormitoryManagement.Models.StudentAccount
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V18</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Resources/Assets/AssetsLogin/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Resources/Assets/Login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Resources/Assets/Login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Resources/Assets/Login/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Resources/Assets/Login/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Resources/Assets/Login/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Resources/Assets/Login/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Resources/Assets/Login/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Resources/Assets/Login/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Resources/Assets/Login/css/main.css">
    <!--===============================================================================================-->
</head>
<body style="background-color: #666666;">

    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                @using (Html.BeginForm("Login", "Access", FormMethod.Post, new { @class = "login100-form validate-form" }))
                {


                    @Html.AntiForgeryToken()

                    <span class="login100-form-title p-b-43">
                        Login to continue
                    </span>


                    <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">

                        @Html.TextBoxFor(m => m.UserName, new
                            {
                            @class = "input100",

                            @id = "exampleInputEmail",
                            required = true
                            })
                        <span class="focus-input100"></span>
                        <span class="label-input100">Email</span>
                    </div>


                    <div class="wrap-input100 validate-input" data-validate="Password is required">
                        @Html.TextBoxFor(m => m.Password, new
                            {
                            @class = "input100",

                            @id = "exampleInputPassword",
                            @type = "password",
                            required = true
                            })
                        <span class="focus-input100"></span>
                        <span class="label-input100">Password</span>
                    </div>

                    <div class="flex-sb-m w-full p-t-3 p-b-32">
                        <div class="contact100-form-checkbox">
                            <!--<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                            //<label class="label-checkbox100" for="ckb1">
                            //    Remember me
                            </label> -->
                        </div>

                        <div>
                            <a href="~/Home/ForgotPassword" class="txt1">
                                Forgot Password?
                            </a>
                        </div>
                    </div>

                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn">
                            Login
                        </button>
                    </div>

                    if (@ViewBag.Error != null)
                    {
                        <div class="form-group">
                            <span class="form-control-user text-danger">@ViewBag.Error</span>
                        </div>
                    }


                }


                <div class="login100-more" style="background-image: url('/Resources/Assets/Login/images/bg-01.jpg');">
                </div>
            </div>
        </div>
    </div>





    <!--===============================================================================================-->
    <script src="~/Resources/Assets/Login/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Resources/Assets/Login/vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Resources/Assets/Login/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Resources/Assets/Login/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Resources/Assets/Login/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Resources/Assets/Login/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/Resources/Assets/Login/vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
    <script src="~/Resources/Assets/Login/vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
    <script src="~/Resources/Assets/Login/js/main.js"></script>

</body>
</html>